// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200821163848_initMig")]
    partial class initMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bussiness_Logic.Models.Clients.Client", b =>
                {
                    b.Property<int>("Id_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("NumeroDoc")
                        .HasColumnType("int")
                        .HasMaxLength(18);

                    b.HasKey("Id_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Invoices.Invoice", b =>
                {
                    b.Property<int>("Id_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientsId_Client")
                        .HasColumnType("int");

                    b.Property<int>("CodeStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFac")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusesCodeStatus")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasMaxLength(18);

                    b.Property<int>("_IdClient")
                        .HasColumnType("int");

                    b.HasKey("Id_Factura");

                    b.HasIndex("ClientsId_Client");

                    b.HasIndex("StatusesCodeStatus");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Invoices.Invoice_Status", b =>
                {
                    b.Property<int>("CodeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("CodeStatus");

                    b.ToTable("Invoice_Statuses");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Invoices.Invoice", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.Clients.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsId_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Logic.Models.Invoices.Invoice_Status", "Statuses")
                        .WithMany()
                        .HasForeignKey("StatusesCodeStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
